version: '3'

services:
  elrond-rosetta-observer-mainnet:
    ulimits:
      nproc: 65535
    image: elrond-rosetta:latest
    container_name: elrond-rosetta-observer-mainnet
    ports:
      - "${PORT_OBSERVER}:8080"
      - "${PORT_P2P}:37373"
    volumes:
      - ${DATA_FOLDER_OBSERVER}:/data
    command: start-observer network=mainnet --destination-shard-as-observer=${OBSERVER_ACTUAL_SHARD} --log-save --log-level=${LOG_LEVEL} --log-logger-name --rest-api-interface=0.0.0.0:8080 --working-directory=/data --validator-key-pem-file=/data/observerKey.pem
    networks:
      elrond-rosetta-mainnet:
        ipv4_address: 10.0.0.10

  elrond-rosetta-online-mainnet:
    image: elrond-rosetta:latest
    container_name: elrond-rosetta-online-mainnet
    ports:
      - "${PORT_ROSETTA_ONLINE}:8080"
    volumes:
      - ${DATA_FOLDER_ROSETTA_ONLINE}:/data
    command: start-rosetta --port 8080 --observer-http-url=http://10.0.0.10:8080 --observer-pubkey=${OBSERVER_PUBKEY} --network-id=1 --network-name=mainnet --num-shards=3 --observer-actual-shard=${OBSERVER_ACTUAL_SHARD} --observer-projected-shard=${OBSERVER_PROJECTED_SHARD} --genesis-block=${GENESIS_BLOCK} --genesis-timestamp=${GENESIS_TIMESTAMP} --native-currency=EGLD --num-historical-blocks=${NUM_HISTORICAL_BLOCKS} --logs-folder=/data
    networks:
      elrond-rosetta-mainnet:
        ipv4_address: 10.0.0.21

  elrond-rosetta-offline-mainnet:
    image: elrond-rosetta:latest
    container_name: elrond-rosetta-offline-mainnet
    ports:
      - "${PORT_ROSETTA_OFFLINE}:8080"
    volumes:
      - ${DATA_FOLDER_ROSETTA_OFFLINE}:/data
    command: start-rosetta --port 8080 --offline --observer-http-url=http://nowhere.localhost.local --network-id=1 --network-name=mainnet --num-shards=3 --observer-actual-shard=${OBSERVER_ACTUAL_SHARD} --observer-projected-shard=${OBSERVER_PROJECTED_SHARD} --genesis-block=${GENESIS_BLOCK} --genesis-timestamp=${GENESIS_TIMESTAMP} --native-currency=EGLD --num-historical-blocks=${NUM_HISTORICAL_BLOCKS} --logs-folder=/data
    networks:
      elrond-rosetta-mainnet:
        ipv4_address: 10.0.0.22

networks:
  elrond-rosetta-mainnet:
    ipam:
      config:
        - subnet: 10.0.0.0/24
