version: '3'

services:
  multiversx-rosetta-observer-mainnet:
    ulimits:
      nproc: 65535
    user: ${DOCKER_USER}
    image: multiversx-rosetta:latest
    container_name: multiversx-rosetta-observer-mainnet
    ports:
      - "${PORT_OBSERVER}:8080"
      - "${PORT_P2P}:37373"
    volumes:
      - ${DATA_FOLDER_OBSERVER}:/data
    command: start-observer network=mainnet --destination-shard-as-observer=${OBSERVER_ACTUAL_SHARD} --display-name=${OBSERVER_DISPLAY_NAME} --log-save --log-level=${LOG_LEVEL} --log-logger-name --rest-api-interface=0.0.0.0:8080 --working-directory=/data --validator-key-pem-file=/data/observerKey.pem
    networks:
      multiversx-rosetta-mainnet:
        ipv4_address: 10.0.0.10

  multiversx-rosetta-online-mainnet:
    user: ${DOCKER_USER}
    image: multiversx-rosetta:latest
    container_name: multiversx-rosetta-online-mainnet
    ports:
      - "${PORT_ROSETTA_ONLINE}:8080"
    volumes:
      - ${DATA_FOLDER_ROSETTA_ONLINE}:/data
    command: start-rosetta --port 8080 --observer-http-url=http://10.0.0.10:8080 --blockchain=${BLOCKCHAIN_NAME} --network-id=1 --network-name=mainnet --num-shards=3 --observer-actual-shard=${OBSERVER_ACTUAL_SHARD} --observer-projected-shard=${OBSERVER_PROJECTED_SHARD} --genesis-block=${GENESIS_BLOCK} --genesis-timestamp=${GENESIS_TIMESTAMP} --first-historical-epoch=${FIRST_HISTORICAL_EPOCH} --num-historical-epochs=${NUM_HISTORICAL_EPOCHS} --native-currency=EGLD --logs-folder=/data
    networks:
      multiversx-rosetta-mainnet:
        ipv4_address: 10.0.0.21

  multiversx-rosetta-offline-mainnet:
    user: ${DOCKER_USER}
    image: multiversx-rosetta:latest
    container_name: multiversx-rosetta-offline-mainnet
    ports:
      - "${PORT_ROSETTA_OFFLINE}:8080"
    volumes:
      - ${DATA_FOLDER_ROSETTA_OFFLINE}:/data
    command: start-rosetta --port 8080 --offline --observer-http-url=http://nowhere.localhost.local --blockchain=${BLOCKCHAIN_NAME} --network-id=1 --network-name=mainnet --num-shards=3 --observer-actual-shard=${OBSERVER_ACTUAL_SHARD} --observer-projected-shard=${OBSERVER_PROJECTED_SHARD} --genesis-block=${GENESIS_BLOCK} --genesis-timestamp=${GENESIS_TIMESTAMP} --first-historical-epoch=${FIRST_HISTORICAL_EPOCH} --num-historical-epochs=${NUM_HISTORICAL_EPOCHS} --native-currency=EGLD --logs-folder=/data
    networks:
      multiversx-rosetta-mainnet:
        ipv4_address: 10.0.0.22

networks:
  multiversx-rosetta-mainnet:
    ipam:
      config:
        - subnet: 10.0.0.0/24
